package com.example.carrental.entity;

public enum Category {
    SEDAN, COUPE, SPORTCAR, STATION_WAGON, HATCHBACK, CONVERTIBLE, SUV, MINIVAN, PICKUP, JEEP, ELECTRIC, CUV, SPYDER, HOT_HATCH, LIMOUSINE, UTE, PONY_CAR, SPORTS_SEDAN
}
